{{ 
  config(
    schema='br_ms_sinan',
    materialized='table',
     partition_by={
      "field": "ano",
      "data_type": "int64",
      "range": {
        "start": 2008,
        "end": 2025,
        "interval": 1}
    },
    labels =  {'tema': 'saude'}
    )
 }}

SELECT 
SAFE_CAST(ano AS INT64) ano,
SAFE_CAST(sigla_uf AS STRING) sigla_uf,
SAFE_CAST(data_notificacao AS DATE) data_notificacao,
SAFE_CAST(id_municipio_notificacao AS STRING) id_municipio_notificacao,
SAFE_CAST(id_municipio_6_notificacao AS STRING) id_municipio_6_notificacao,
SAFE_CAST(sistema AS STRING) sistema,
SAFE_CAST(id_estabelecimento_cnes AS STRING) id_estabelecimento_cnes,
SAFE_CAST(semana_notificacao AS INT64) semana_notificacao,
SAFE_CAST(data_primeiros_sintomas AS DATE) data_primeiros_sintomas,
SAFE_CAST(semana_sintomas AS INT64) semana_sintomas,
SAFE_CAST(SAFE_CAST(paciente_estrangeiro AS NUMERIC) AS STRING) paciente_estrangeiro,
SAFE_CAST(pais_residencia AS STRING) pais_residencia,
SAFE_CAST(sigla_uf_residencia AS STRING) sigla_uf_residencia,
SAFE_CAST(id_municipio_residencia AS STRING) id_municipio_residencia,
SAFE_CAST(id_municipio_6_residencia AS STRING) id_municipio_6_residencia,
SAFE_CAST(SAFE_CAST(zona_residencia AS NUMERIC) AS STRING) zona_residencia,
SAFE_CAST(SAFE_CAST(caso_natural_residencia AS NUMERIC) AS STRING) caso_natural_residencia,
SAFE_CAST(data_nascimento AS STRING) data_nascimento,
SAFE_CAST(SAFE_CAST(sexo AS NUMERIC) AS STRING)  sexo,
SAFE_CAST(SAFE_CAST(raca_cor AS NUMERIC) AS STRING) raca_cor,
SAFE_CAST(etnia AS STRING) etnia,
SAFE_CAST(SAFE_CAST(gestante AS NUMERIC) AS STRING) gestante,
SAFE_CAST(SAFE_CAST(puerpera AS NUMERIC) AS STRING) puerpera,
SAFE_CAST(SAFE_CAST(escolaridade AS NUMERIC) AS STRING) escolaridade,
SAFE_CAST(SAFE_CAST(ocupacao AS NUMERIC) AS STRING) ocupacao,
SAFE_CAST(SAFE_CAST(doenca_relacionada_trabalho AS NUMERIC) AS STRING) doenca_relacionada_trabalho,
SAFE_CAST(SAFE_CAST(tabagista AS NUMERIC) AS STRING) tabagista,
SAFE_CAST(SAFE_CAST(sindrome_gripal AS NUMERIC) AS STRING) sindrome_gripal,
SAFE_CAST(SAFE_CAST(infeccao_hospitalar AS NUMERIC) AS STRING) infeccao_hospitalar,
SAFE_CAST(SAFE_CAST(contato_aves_suinos AS NUMERIC) AS STRING) contato_aves_suinos,
SAFE_CAST(SAFE_CAST(contato_outro_animal AS NUMERIC) AS STRING) contato_outro_animal,
SAFE_CAST(SAFE_CAST(apresenta_febre AS NUMERIC) AS STRING) apresenta_febre,
SAFE_CAST(SAFE_CAST(apresenta_tosse AS NUMERIC) AS STRING) apresenta_tosse,
SAFE_CAST(SAFE_CAST(apresenta_calafrio AS NUMERIC) AS STRING) apresenta_calafrio,
SAFE_CAST(SAFE_CAST(apresenta_dor_garganta AS NUMERIC) AS STRING) apresenta_dor_garganta,
SAFE_CAST(SAFE_CAST(apresenta_dispneia AS NUMERIC) AS STRING) apresenta_dispneia,
SAFE_CAST(SAFE_CAST(apresenta_artralgia AS NUMERIC) AS STRING) apresenta_artralgia,
SAFE_CAST(SAFE_CAST(apresenta_mialgia AS NUMERIC) AS STRING) apresenta_mialgia,
SAFE_CAST(SAFE_CAST(apresenta_conjuntivite AS NUMERIC) AS STRING) apresenta_conjuntivite,
SAFE_CAST(SAFE_CAST(apresenta_coriza AS NUMERIC) AS STRING) apresenta_coriza,
SAFE_CAST(SAFE_CAST(apresenta_desconforto_respiratorio AS NUMERIC) AS STRING) apresenta_desconforto_respiratorio,
SAFE_CAST(SAFE_CAST(apresenta_saturacao_anormal AS NUMERIC) AS STRING) apresenta_saturacao_anormal,
SAFE_CAST(SAFE_CAST(apresenta_diarreia AS NUMERIC) AS STRING) apresenta_diarreia,
SAFE_CAST(SAFE_CAST(apresenta_vomito AS NUMERIC) AS STRING) apresenta_vomito,
SAFE_CAST(SAFE_CAST(apresenta_dor_abdominal AS NUMERIC) AS STRING) apresenta_dor_abdominal,
SAFE_CAST(SAFE_CAST(apresenta_fadiga AS NUMERIC) AS STRING) apresenta_fadiga,
SAFE_CAST(SAFE_CAST(apresenta_perda_olfato AS NUMERIC) AS STRING) apresenta_perda_olfato,
SAFE_CAST(SAFE_CAST(apresenta_perda_paladar AS NUMERIC) AS STRING) apresenta_perda_paladar,
SAFE_CAST(SAFE_CAST(apresenta_outros_sintomas AS NUMERIC) AS STRING) apresenta_outros_sintomas,
SAFE_CAST(qual_outro_sintoma AS STRING) qual_outro_sintoma,
SAFE_CAST(SAFE_CAST(apresenta_fator_risco AS NUMERIC) AS STRING) apresenta_fator_risco,
SAFE_CAST(SAFE_CAST(possui_cardiopatia AS NUMERIC) AS STRING) possui_cardiopatia,
SAFE_CAST(SAFE_CAST(possui_pneumopatia AS NUMERIC) AS STRING) possui_pneumopatia,
SAFE_CAST(SAFE_CAST(possui_hemoglobinopatia AS NUMERIC) AS STRING) possui_hemoglobinopatia,
SAFE_CAST(SAFE_CAST(possui_doenca_metabolica AS NUMERIC) AS STRING) possui_doenca_metabolica,
SAFE_CAST(SAFE_CAST(possui_sindrome_down AS NUMERIC) AS STRING) possui_sindrome_down,
SAFE_CAST(SAFE_CAST(possui_hepatite AS NUMERIC) AS STRING) possui_hepatite,
SAFE_CAST(SAFE_CAST(possui_doenca_neurologica AS NUMERIC) AS STRING) possui_doenca_neurologica,
SAFE_CAST(SAFE_CAST(possui_imunodeficiencia AS NUMERIC) AS STRING) possui_imunodeficiencia,
SAFE_CAST(SAFE_CAST(possui_doenca_renal AS NUMERIC) AS STRING) possui_doenca_renal,
SAFE_CAST(SAFE_CAST(possui_obesidade AS NUMERIC) AS STRING) possui_obesidade,
SAFE_CAST(imc_obeso AS STRING) imc_obeso,
SAFE_CAST(SAFE_CAST(possui_hematologia AS NUMERIC) AS STRING) possui_hematologia,
SAFE_CAST(SAFE_CAST(possui_asma AS NUMERIC) AS STRING) possui_asma,
SAFE_CAST(SAFE_CAST(possui_diabetes AS NUMERIC) AS STRING) possui_diabetes,
SAFE_CAST(SAFE_CAST(possui_outra_morbidade AS NUMERIC) AS STRING) possui_outra_morbidade,
SAFE_CAST(qual_outra_morbidade AS STRING) qual_outra_morbidade,
SAFE_CAST(SAFE_CAST(vacina_gripe AS NUMERIC) AS STRING) vacina_gripe,
SAFE_CAST(data_ultima_dose AS DATE) data_ultima_dose,
SAFE_CAST(SAFE_CAST(vacina_gripe_mae AS NUMERIC) AS STRING) vacina_gripe_mae,
SAFE_CAST(data_vacina_mae AS DATE) data_vacina_mae,
SAFE_CAST(SAFE_CAST(mae_amamenta AS NUMERIC) AS STRING) mae_amamenta,
SAFE_CAST(data_vacina_crianca_dose_unica AS DATE) data_vacina_crianca_dose_unica,
SAFE_CAST(data_vacina_crianca_1dose AS DATE) data_vacina_crianca_1dose,
SAFE_CAST(data_vacina_crianca_2dose AS DATE) data_vacina_crianca_2dose,
SAFE_CAST(SAFE_CAST(vacina_covid AS NUMERIC) AS STRING) vacina_covid,
SAFE_CAST(data_vacina_covid_dose_1 AS DATE) data_vacina_covid_dose1,
SAFE_CAST(data_vacina_covid_dose_2 AS DATE) data_vacina_covid_dose2,
SAFE_CAST(laboratorio_vacina_covid AS STRING) laboratorio_vacina_covid,
SAFE_CAST(lote_dose1_vacina_covid AS STRING) lote_dose1_vacina_covid,
SAFE_CAST(lote_dose2_vacina_covid AS STRING) lote_dose2_vacina_covid,
SAFE_CAST(SAFE_CAST(fonte_dados_vacina_covid AS NUMERIC) AS STRING) fonte_dados_vacina_covid,
SAFE_CAST(SAFE_CAST(antiviral_gripe AS NUMERIC) AS STRING) antiviral_gripe,
SAFE_CAST(SAFE_CAST(tipo_antiviral AS NUMERIC) AS STRING) tipo_antiviral,
SAFE_CAST(outro_tipo_antiviral AS STRING) outro_tipo_antiviral,
SAFE_CAST(data_tratamento_antiviral AS DATE) data_tratamento_antiviral,
SAFE_CAST(SAFE_CAST(internacao AS NUMERIC) AS STRING) internacao,
SAFE_CAST(data_internacao AS DATE) data_internacao,
SAFE_CAST(sigla_uf_internacao AS STRING) sigla_uf_internacao,
SAFE_CAST(SAFE_CAST(id_regional_saude_internacao AS NUMERIC) AS STRING) id_regional_saude_internacao,
SAFE_CAST(SAFE_CAST(id_municipio_internacao AS NUMERIC) AS STRING) id_municipio_internacao,
SAFE_CAST(SAFE_CAST(id_municipio_6_internacao AS NUMERIC) AS STRING) id_municipio_6_internacao,
SAFE_CAST(SAFE_CAST(internacao_uti AS NUMERIC) AS STRING) internacao_uti,
SAFE_CAST(data_entrada_uti AS DATE) data_entrada_uti,
SAFE_CAST(data_saida_uti AS DATE) data_saida_uti,
SAFE_CAST(SAFE_CAST(suporte_ventilatorio AS NUMERIC) AS STRING) suporte_ventilatorio,
SAFE_CAST(SAFE_CAST(resultado_raiox_torax AS NUMERIC) AS STRING) resultado_raiox_torax,
SAFE_CAST(SAFE_CAST(outro_resultado_raiox AS NUMERIC) AS STRING) outro_resultado_raiox,
SAFE_CAST(data_raiox AS DATE) data_raiox,
SAFE_CAST(SAFE_CAST(resultado_tomografia AS NUMERIC) AS STRING) resultado_tomografia,
SAFE_CAST(outro_resultado_tomografia AS STRING) outro_resultado_tomografia,
SAFE_CAST(data_tomografia AS DATE) data_tomografia,
SAFE_CAST(SAFE_CAST(coleta_amostra AS NUMERIC) AS STRING) coleta_amostra,
SAFE_CAST(data_coleta AS DATE) data_coleta,
SAFE_CAST(SAFE_CAST(tipo_amostra AS NUMERIC) AS STRING) tipo_amostra,
SAFE_CAST(outro_tipo_amostra AS STRING) outro_tipo_amostra,
SAFE_CAST(SAFE_CAST(resultado_amostra AS NUMERIC) AS STRING) resultado_amostra,
SAFE_CAST(data_coleta_hemaglutinacao AS DATE) data_coleta_hemaglutinacao,
SAFE_CAST(SAFE_CAST(resultado_hemaglutinacao AS NUMERIC) AS STRING) resultado_hemaglutinacao,
SAFE_CAST(SAFE_CAST(tipo_resultado_hemaglutinacao AS NUMERIC) AS STRING) tipo_resultado_hemaglutinacao,
SAFE_CAST(SAFE_CAST(hemaglutinacao_tipo_hemaglutinina AS NUMERIC) AS STRING) hemaglutinacao_tipo_hemaglutinina,
SAFE_CAST(SAFE_CAST(hemaglutinacao_tipo_neuraminidase AS NUMERIC) AS STRING) hemaglutinacao_tipo_neuraminidase,
SAFE_CAST(SAFE_CAST(tipo_pcr AS NUMERIC) AS STRING) tipo_pcr,
SAFE_CAST(data_coleta_pcr AS DATE) data_coleta_pcr,
SAFE_CAST(SAFE_CAST(tipo_amostra_pcr AS NUMERIC) AS STRING) tipo_amostra_pcr,
SAFE_CAST(qual_outro_tipo_amostra_pcr AS STRING) qual_outro_tipo_amostra_pcr,
SAFE_CAST(data_resultado_pcr AS STRING) data_resultado_pcr,
SAFE_CAST(SAFE_CAST(resultado_pcr AS NUMERIC) AS STRING) resultado_pcr,
SAFE_CAST(SAFE_CAST(diagnostico_pcr AS NUMERIC) AS STRING) diagnostico_pcr,
SAFE_CAST(SAFE_CAST(id_laboratorio_pcr AS NUMERIC) AS STRING) id_laboratorio_pcr,
SAFE_CAST(SAFE_CAST(tipo_resultado_pcr AS NUMERIC) AS STRING) tipo_resultado_pcr,
SAFE_CAST(SAFE_CAST(pcr_tipo_hemaglutinina AS NUMERIC) AS STRING) pcr_tipo_hemaglutinina,
SAFE_CAST(SAFE_CAST(pcr_tipo_neuraminidase AS NUMERIC) AS STRING) pcr_tipo_neuraminidase,
SAFE_CAST(SAFE_CAST(pcr_positivo_influenza AS NUMERIC) AS STRING) pcr_positivo_influenza,
SAFE_CAST(SAFE_CAST(tipo_influenza_pcr AS NUMERIC) AS STRING) tipo_influenza_pcr,
SAFE_CAST(SAFE_CAST(subtipo_influenza_a AS NUMERIC) AS STRING) subtipo_influenza_a,
SAFE_CAST(outro_subtitpo_influenza AS STRING) outro_subtitpo_influenza,
SAFE_CAST(SAFE_CAST(linhagem_influeza_b as NUMERIC) AS STRING) linhagem_influeza_b,
SAFE_CAST(outra_linhagem_influenza_b AS STRING) outra_linhagem_influenza_b,
SAFE_CAST(SAFE_CAST(pcr_positivo_outro_virus AS NUMERIC) AS STRING) pcr_positivo_outro_virus,
SAFE_CAST(SAFE_CAST(pcr_sarscov2 AS NUMERIC) AS INT64) pcr_sarscov2,
SAFE_CAST(SAFE_CAST(pcr_virus_sincicial_respiratorio AS NUMERIC) AS INT64) pcr_virus_sincicial_respiratorio,
SAFE_CAST(SAFE_CAST(pcr_parainfluenza_1 AS NUMERIC) AS STRING) pcr_parainfluenza_1,
SAFE_CAST(SAFE_CAST(pcr_parainfluenza_2 AS NUMERIC) AS STRING) pcr_parainfluenza_2,
SAFE_CAST(SAFE_CAST(pcr_parainfluenza_3 AS NUMERIC) AS STRING) pcr_parainfluenza_3,
SAFE_CAST(SAFE_CAST(pcr_parainfluenza_4 AS NUMERIC) AS STRING) pcr_parainfluenza_4,
SAFE_CAST(SAFE_CAST(pcr_adenovirus AS NUMERIC) AS INT64) pcr_adenovirus,
SAFE_CAST(SAFE_CAST(pcr_metapneumovirus AS NUMERIC) AS INT64) pcr_metapneumovirus,
SAFE_CAST(SAFE_CAST(pcr_bocavirus AS NUMERIC) AS INT64) pcr_bocavirus,
SAFE_CAST(SAFE_CAST(pcr_rinovirus AS NUMERIC) AS INT64) pcr_rinovirus,
SAFE_CAST(SAFE_CAST(pcr_outro_virus AS NUMERIC) AS STRING) pcr_outro_virus,
SAFE_CAST(qual_outro_virus AS STRING) qual_outro_virus,
SAFE_CAST(SAFE_CAST(diagnostico_imunofluorescencia AS NUMERIC) AS STRING) diagnostico_imunofluorescencia,
SAFE_CAST(SAFE_CAST(resultado_imunofluorescencia AS NUMERIC) AS STRING) resultado_imunofluorescencia,
SAFE_CAST(data_resultado_imunofluorescencia AS DATE) data_resultado_imunofluorescencia,
SAFE_CAST(SAFE_CAST(id_laboratorio_imunofluorescencia AS NUMERIC) AS STRING) id_laboratorio_imunofluorescencia,
SAFE_CAST(SAFE_CAST(diagnostico_influenza_a AS NUMERIC) AS STRING) diagnostico_influenza_a,
SAFE_CAST(SAFE_CAST(diagnostico_subtipo_influenza_a AS NUMERIC) AS STRING) diagnostico_subtipo_influenza_a,
SAFE_CAST(SAFE_CAST(diagnostico_influenza_b AS NUMERIC) AS STRING) diagnostico_influenza_b,
SAFE_CAST(SAFE_CAST(diagnostico_virus_sincicial_respiratorio AS NUMERIC) AS STRING) diagnostico_virus_sincicial_respiratorio,
SAFE_CAST(SAFE_CAST(diagnostico_parainfluenza_1 AS NUMERIC) AS STRING) diagnostico_parainfluenza_1,
SAFE_CAST(SAFE_CAST(diagnostico_parainfluenza_2 AS NUMERIC) AS STRING) diagnostico_parainfluenza_2,
SAFE_CAST(SAFE_CAST(diagnostico_parainfluenza_3 AS NUMERIC) AS STRING) diagnostico_parainfluenza_3,
SAFE_CAST(SAFE_CAST(diagnostico_adenovirus AS NUMERIC) AS STRING) diagnostico_adenovirus,
SAFE_CAST(SAFE_CAST(diagnostico_outro_virus AS NUMERIC) AS STRING) diagnostico_outro_virus,
SAFE_CAST(SAFE_CAST(diagnostico_outra_metodologia AS NUMERIC) AS STRING) diagnostico_outra_metodologia,
SAFE_CAST(SAFE_CAST(imunofluorescencia_positivo_influenza AS NUMERIC) AS STRING) imunofluorescencia_positivo_influenza,
SAFE_CAST(SAFE_CAST(tipo_influenza_imunofluorescencia AS NUMERIC) AS STRING) tipo_influenza_imunofluorescencia,
SAFE_CAST(SAFE_CAST(imunofluorescencia_positivo_outro_virus AS NUMERIC) AS STRING) imunofluorescencia_positivo_outro_virus,
SAFE_CAST(SAFE_CAST(imunofluorescencia_virus_sincicial_respiratorio AS NUMERIC) AS STRING) imunofluorescencia_virus_sincicial_respiratorio,
SAFE_CAST(SAFE_CAST(imunofluorescencia_parainfluenza_1 AS NUMERIC) AS STRING) imunofluorescencia_parainfluenza_1,
SAFE_CAST(SAFE_CAST(imunofluorescencia_parainfluenza_2 AS NUMERIC) AS STRING) imunofluorescencia_parainfluenza_2,
SAFE_CAST(SAFE_CAST(imunofluorescencia_parainfluenza_3 AS NUMERIC) AS STRING) imunofluorescencia_parainfluenza_3,
SAFE_CAST(SAFE_CAST(imunofluorescencia_adenovirus AS NUMERIC) AS STRING) imunofluorescencia_adenovirus,
SAFE_CAST(SAFE_CAST(imunofluorescencia_outro_virus AS NUMERIC) AS STRING) imunofluorescencia_outro_virus,
SAFE_CAST(SAFE_CAST(imunofluorescencia_qual_outro_virus AS NUMERIC) AS STRING) imunofluorescencia_qual_outro_virus,
SAFE_CAST(SAFE_CAST(tipo_teste_antigenico AS NUMERIC) AS STRING) tipo_teste_antigenico,
SAFE_CAST(data_resultado_teste AS DATE) data_resultado_teste,
SAFE_CAST(SAFE_CAST(resultado_teste_antigenico AS NUMERIC) AS STRING) resultado_teste_antigenico,
SAFE_CAST(SAFE_CAST(teste_positivo_influenza AS NUMERIC) AS STRING) teste_positivo_influenza,
SAFE_CAST(SAFE_CAST(tipo_influenza_teste AS NUMERIC) AS STRING) tipo_influenza_teste,
SAFE_CAST(SAFE_CAST(teste_positivo_outro_virus AS NUMERIC) AS STRING) teste_positivo_outro_virus,
SAFE_CAST(SAFE_CAST(teste_sarscov2 AS NUMERIC) AS STRING) teste_sarscov2,
SAFE_CAST(SAFE_CAST(teste_virus_sincicial_respiratorio AS NUMERIC) AS INT64) teste_virus_sincicial_respiratorio,
SAFE_CAST(SAFE_CAST(teste_parainfluenza_1 AS NUMERIC) AS STRING) teste_parainfluenza_1,
SAFE_CAST(SAFE_CAST(teste_parainfluenza_2 AS NUMERIC) AS STRING) teste_parainfluenza_2,
SAFE_CAST(SAFE_CAST(teste_parainfluenza_3 AS NUMERIC) AS STRING) teste_parainfluenza_3,
SAFE_CAST(SAFE_CAST(teste_adenovirus AS NUMERIC) AS INT64) teste_adenovirus,
SAFE_CAST(SAFE_CAST(teste_outro_virus AS NUMERIC) AS INT64) teste_outro_virus,
SAFE_CAST(teste_outro_virus_nome AS STRING) teste_outro_virus_nome,
SAFE_CAST(SAFE_CAST(tipo_amostra_sorologica AS NUMERIC) AS STRING) tipo_amostra_sorologica,
SAFE_CAST(qual_outra_amostra AS STRING) qual_outra_amostra,
SAFE_CAST(data_coleta_amostra AS DATE) data_coleta_amostra,
SAFE_CAST(SAFE_CAST(tipo_sorologia AS NUMERIC) AS STRING) tipo_sorologia,
SAFE_CAST(qual_outra_sorologia AS STRING) qual_outra_sorologia,
SAFE_CAST(data_resultado_sorologia AS DATE) data_resultado_sorologia,
SAFE_CAST(SAFE_CAST(resultado_sorologia_igg AS NUMERIC) AS STRING) resultado_sorologia_igg,
SAFE_CAST(SAFE_CAST(resultado_sorologia_igm AS NUMERIC) AS STRING) resultado_sorologia_igm,
SAFE_CAST(SAFE_CAST(resultado_sorologia_iga AS NUMERIC) AS STRING) resultado_sorologia_iga,
SAFE_CAST(SAFE_CAST(historico_viagem AS NUMERIC) AS STRING) historico_viagem,
SAFE_CAST(pais_viagem AS STRING) pais_viagem,
SAFE_CAST(local_viagem AS STRING) local_viagem,
SAFE_CAST(data_viagem AS DATE) data_viagem_paciente,
SAFE_CAST(data_retorno AS DATE) data_retorno_paciente,
SAFE_CAST(SAFE_CAST(status_monitoramento AS NUMERIC) AS STRING) status_monitoramento,
SAFE_CAST(SAFE_CAST(classificacao_final AS NUMERIC) AS STRING) classificacao_final,
SAFE_CAST(outro_agente_etiologico AS STRING) outro_agente_etiologico,
SAFE_CAST(SAFE_CAST(criterio_encerramento AS NUMERIC) AS STRING) criterio_encerramento,
SAFE_CAST(SAFE_CAST(evolucao_caso AS NUMERIC) AS STRING) evolucao_caso,
SAFE_CAST(data_alta_obito AS DATE) data_alta_obito,
SAFE_CAST(data_encerramento AS DATE) data_encerramento,
SAFE_CAST(data_digitacao AS DATE) data_digitacao,
SAFE_CAST(SAFE_CAST(tipo_ficha AS NUMERIC) AS STRING) tipo_ficha,
SAFE_CAST(requisicao_sistema_gal AS STRING) requisicao_sistema_gal,
SAFE_CAST(SAFE_CAST(controle_srag_sinan AS NUMERIC) AS STRING) controle_srag_sinan
FROM basedosdados-staging.br_ms_sinan_staging.microdados_influenza_srag AS t