# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "basedosdados"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Grant acess
# bq data control: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-control-language
# dbt grant statements use https://discourse.getdbt.com/t/the-exact-grant-statements-we-use-in-a-dbt-project/430

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
  
# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +post-hook: 'GRANT `roles/bigquery.dataViewer` ON TABLE {{ this }} TO "specialGroup:allUsers"'
  +persist_docs:
    relation: true
    columns: true
  basedosdados:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: table # Materialization type (table, table or incremental)
      +schema: example # Overrides the default schema (defaults to what is set on profiles.yml)
    br_b3_cotacoes:
      +materialized: table
      +schema: br_b3_cotacoes 
    br_anatel_banda_larga_fixa:
      +materialized: table
      +schema: br_anatel_banda_larga_fixa
    br_tse_eleicoes_2022:
      +materialized: table
      +schema: br_tse_eleicoes_2022
    br_bd_indicadores:
      +materialized: table
      +schema: br_bd_indicadores
    br_bd_metadados:
      +materialized: table
      +schema: br_bd_metadados
    br_sp_saopaulo_dieese_icv:
      +materialized: table
      +schema: br_sp_saopaulo_dieese_icv
    br_cgu_pessoal_executivo_federal:
      +materialized: table
      +schema: br_cgu_pessoal_executivo_federal
    br_cvm_administradores_carteira:
      +materialized: table
      +schema: br_cvm_administradores_carteira
    br_cvm_oferta_publica_distribuicao:
      +materialized: table
      +schema: br_cvm_oferta_publica_distribuicao
    br_fgv_igp:
      +materialized: table
      +schema: br_fgv_igp
    br_ibge_inpc:
      +materialized: table
      +schema: br_ibge_inpc
    br_ibge_ipca:
      +materialized: table
      +schema: br_ibge_ipca
    br_ibge_ipca15:
      +materialized: table
      +schema: br_ibge_ipca15
    br_poder360_pesquisas:
      +materialized: table
      +schema: br_poder360_pesquisas
    fundacao_lemann:
      +materialized: table
      +schema: fundacao_lemann
    br_tse_eleicoes:
      +materialized: table
      +schema: br_tse_eleicoes
    br_jota:
      +materialized: table
      +schema: br_jota
    br_ibge_pnadc:
      +materialized: table
      +schema: br_ibge_pnadc
    br_bcb_estban:
      +materialized: table
      +schema: br_bcb_estban 
    br_inmet_bdmep:
      +materialized: table
      +schema: br_inmet_bdmep      
    test_dataset:
      +materialized: table
      +schema: test_dataset
    br_me_comex_stat:
      +materialized: table
      +schema: br_me_comex_stat
    br_ons_avaliacao_operacao:
      +materialized: table
      +schema: br_ons_avaliacao_operacao  
    br_cvm_fi:
      +materialized: table
      +schema: br_cvm_fi
    br_ons_estimativa_custos:
      +materialized: table
      +schema: br_ons_estimativa_custos
