{{ config(alias='microdados',schema='br_ms_sisvan') }}
select
safe_cast(ano as int64) ano,
safe_cast(mes as int64) mes,
safe_cast(sigla_uf as string) sigla_uf,
safe_cast(id_municipio as string) id_municipio,
safe_cast(acompanhamento as string) acompanhamento,
safe_cast(id_individuo  as string) id_individuo ,
safe_cast(cnes as string) cnes,
safe_cast(idade as int64) idade,
safe_cast(fase_vida as string) fase_vida,
safe_cast(sexo as string) sexo,
safe_cast(raca_cor as string) raca_cor,
safe_cast(povo_comunidade as string) povo_comunidade,
safe_cast(escolaridade as string) escolaridade,
safe_cast(data_acompanhamento as date) data_acompanhamento,
safe_cast(peso as float64) peso,
safe_cast(altura as float64) altura,
safe_cast(imc as float64) imc,
safe_cast(imc_gestacional as float64) imc_gestacional,
safe_cast(estado_nutricional_peso_idade_crianca as string) estado_nutricional_peso_idade_crianca,
safe_cast(estado_nutricional_peso_altura_crianca as string) estado_nutricional_peso_altura_crianca,
safe_cast(estado_nutricional_altura_idade_crianca as string) estado_nutricional_altura_idade_crianca,
safe_cast(estado_nutricional_imc_idade_crianca as string) estado_nutricional_imc_idade_crianca,
safe_cast(estado_nutricional_altura_idade_adolescente as string) estado_nutricional_altura_idade_adolescente,
safe_cast(estado_nutricional_imc_idade_adolescente as string) estado_nutricional_imc_idade_adolescente,
safe_cast(estado_nutricional_adulto  as string) estado_nutricional_adulto ,
safe_cast(estado_nutricional_idoso as string) estado_nutricional_idoso,
safe_cast(estado_nutricional_gestantes as string) estado_nutricional_gestantes,
safe_cast(sistema_origem as string) sistema_origem,
from `basedosdados-dev.br_ms_sisvan_staging.microdados` as t

