version: 2
models :
  - name: columns
    description: Colunas na BD+
    columns:
      - name: bigquery_type
        description: Bigquery Type
      - name: covered_by_dictionary
        description: Indicates if it is covered by dictionary
      - name: description
        description: Description
      - name: directory_column
        description: Directory Column
      - name: has_sensitive_data
        description: Indicates if it has sensitive data
      - name: is_in_staging
        description: Is in staging
      - name: is_partition
        description: Is Partition
      - name: measurement_unit
        description: Measurement Unit
      - name: name
        description: Name
      - name: observations
        description: Observations
      - name: table_id
        description: Table ID
      - name: temporal_coverage
        description: Temporal Coverage
