version: 2

models:
  - name: desmatamento_municipio
    description: Apresenta o desmatamento dos municipios e outras variáveis na Amazônia Legal a partir do ano 2000
    columns:
      - name: ano
        description: Ano
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: bioma
        description: Bioma
      - name: area
        description: Área
      - name: desmatamento
        description: Área Desmatada Total
      - name: floresta
        description: Área de Floresta
      - name: nao_floresta
        description: Área de Não-Floresta
      - name: hidrografia
        description: Área de Hidrografia
