---
name: 🛑 Deactivate
description: Solicitação para desativar o schedule de uma pipeline
title: '[deactivate] <dataset_id>.<table_id>'
labels: [maintenance]
body:
  - type: textarea
    attributes:
      label: 📌 Motivo da Desativação
      description: Explique por que é necessário desativar o schedule da pipeline.
        Inclua detalhes como problemas técnicos, descontinuidade dos dados, mudanças
        no processo, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🛠️ Proposta de Solução
      description: Descreva como a pipeline deve ser desativada. Deve ser temporária
        ou permanente? Alguma ação adicional deve ser tomada?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: ✅ Passo a Passo
      description: Selecione as ações que devem ser realizadas junto com a desativação.
      options:
        - label: Subir o PR para desativar o schedule da Pipeline
        - label: Notificar equipes ou usuários impactados
        - label: Avaliar junto a equipe o tempo necessário para a priorização da tarefa
