---
version: 2
models:
  - name: br_bd_diretorios_brasil__cbo_2002
    description: Diretório da Classificação Brasileira de Ocupações 2002.
    columns:
      - name: cbo_2002
        description: Classificação Brasileira de Ocupações 2002
      - name: descricao
        description: Descrição da CBO2002
      - name: familia
        description: Família
      - name: descricao_familia
        description: Descrição da Família
      - name: subgrupo
        description: Subgrupo
      - name: descricao_subgrupo
        description: Descrição do Subgrupo
      - name: subgrupo_principal
        description: Subgrupo Principal
      - name: descricao_subgrupo_principal
        description: Descrição do Subgrupo Principal
      - name: grande_grupo
        description: Grande Grupo
      - name: descricao_grande_grupo
        description: Descrição do Grande Grupo
      - name: indicador_cbo_2002_ativa
        description: Indica se o código de 6 dígitos da CBO de 2002 permanece ativo
          ou não
  - name: br_bd_diretorios_brasil__empresa
    description: A tabela apresenta informações do Cadastro Nacional da Pessoa Jurídica
      (CNPJ), que é um banco de dados administrado pela Secretaria Especial da Receita
      Federal do Brasil (RFB). Esse cadastro armazena detalhes cadastrais de pessoas
      jurídicas e outras entidades relevantes para as administrações tributárias do
      governo federal, dos estados, do Distrito Federal e dos municípios.
    columns:
      - name: cnpj
        description: CNPJ
      - name: cnpj_basico
        description: CNPJ Básico (8 primeiros dígitos)
      - name: cnpj_ordem
        description: CNPJ Ordem
      - name: cnpj_dv
        description: CNPJ Dígito Verificador
      - name: razao_social
        description: Nome empresarial da pessoa jurídica
      - name: nome_fantasia
        description: Denomização Comercial
      - name: natureza_juridica
        description: Natureza Jurídica
      - name: ente_federativo
        description: Ente Federativo Responsável
      - name: cnae_fiscal_principal
        description: CNAE Fiscal Principal
      - name: cnae_fiscal_secundaria
        description: CNAEs Fiscais Secundárias
      - name: capital_social
        description: Capital Social
      - name: porte
        description: Tipo do porte da empresa
      - name: matriz_filial
        description: Identificador entre Matriz e Filial
      - name: situacao_cadastral
        description: Situação Cadastral
      - name: situacao_especial
        description: Situação Especial
      - name: opcao_simples
        description: Opção pelo Simples Nacional
      - name: opcao_mei
        description: Opção pelo MEI
      - name: cep
        description: CEP
      - name: tipo_logradouro
        description: Tipo de Logradouro
      - name: logradouro
        description: Logradouro
      - name: numero
        description: Número
      - name: complemento
        description: Complemento
      - name: bairro
        description: Bairro
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_code_iso3
        description: Sigla do País - ISO3
      - name: id_pais_me
        description: ID do país - Ministério da Economia
      - name: nome_pais_me
        description: Nome do país - Ministério da Economia
      - name: telefone_1
        description: Telefone (com DDD) 1
      - name: telefone_2
        description: Telefone (com DDD) 2
      - name: fax
        description: Fax (con DDD)
      - name: email
        description: Email
  - name: cep
    description: Na tabela, é possível encontrar a numeração dos CEPs, juntamente
      com informações sobre suas localidades, tais como logradouros, bairros e cidades,
      além de complementos e identificação geográfica compostos pela latitude e longitude.
      Os dados foram obtidos através de uma base aberta no Kaggle e validados em relação
      aos seus pontos de geolocalização.
    columns:
      - name: cep
        description: Número do CEP
      - name: logradouro
        description: Logradouro
      - name: complemento
        description: Complemento do endereço
      - name: bairro
        description: Bairro
      - name: cidade
        description: Nome da cidade, distrito ou município
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: latitude
        description: Latitude do CEP
      - name: longitude
        description: Longitude do CEP
      - name: centroide
        description: Centróide do CEP
  - name: br_bd_diretorios_brasil__municipio
    description: 'Diretório ligando diversos códigos institucionais de municípios
      brasileiros: IBGE, Receita Federal, TSE, BCB, regiões, comarcas, região de saúde,
      etc.'
    columns:
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: id_municipio_6
        description: ID Município - IBGE 6 Dígitos
      - name: id_municipio_tse
        description: ID Município - Tribunal Superior Eleitoral (TSE)
      - name: id_municipio_rf
        description: ID Município - Receita Federal (RF)
      - name: id_municipio_bcb
        description: ID Município - Banco Central do Brasil (BCB)
      - name: nome
        description: Nome do Município
      - name: capital_uf
        description: Município é a Capital da Unidade da Federação
      - name: id_comarca
        description: ID Sede Comarca
      - name: id_regiao_saude
        description: ID Região de Saúde
      - name: nome_regiao_saude
        description: Nome da Região de Saúde
      - name: id_regiao_imediata
        description: ID Região Imediata - IBGE
      - name: nome_regiao_imediata
        description: Nome da Região Imediata
      - name: id_regiao_intermediaria
        description: ID Região Intermediária - IBGE
      - name: nome_regiao_intermediaria
        description: Nome da Região Intermediária
      - name: id_microrregiao
        description: ID Microrregião - IBGE
      - name: nome_microrregiao
        description: Nome da Microrregião
      - name: id_mesorregiao
        description: ID Mesorregião - IBGE
      - name: nome_mesorregiao
        description: Nome da Mesorregião
      - name: id_regiao_metropolitana
        description: ID Região Metropolitana - IBGE
      - name: nome_regiao_metropolitana
        description: Nome da Região Metropolitana
      - name: ddd
        description: Código de Discagem Direta a Distância (DDD)
      - name: id_uf
        description: ID da Unidade da Federação - IBGE
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: nome_uf
        description: Nome da Unidade da Federação
      - name: nome_regiao
        description: Nome da Grande Região Brasileira
      - name: amazonia_legal
        description: Indicador se o município faz parte da Amazônia Legal
      - name: centroide
        description: Centróide do município
  - name: regiao_metropolitana
    description: A tabela contém os códigos identificadores e nomes de Região Metropolitana
      (RM), Aglomeração Urbana (AU), Região Integrada de Desenvolvimento (RIDE) entre
      outros recortes reunidas pelo IBGE
    columns:
      - name: id_regiao_metropolitana
        description: ID Região Metropolitana - IBGE
      - name: nome
        description: Nome da Região Metropolitana
      - name: id_recorte_metropolitano
        description: ID Recorte Metropolitano - IBGE
      - name: nome_recorte_metropolitano
        description: Nome do Recorte Metropolitano
      - name: id_subcategoria_metropolitana
        description: ID Subcategoria Metropolitana - IBGE
      - name: nome_subcategoria_metropolitana
        description: Nome Subcategoria Metropolitana
      - name: tipo
        description: Tipo da Região
      - name: id_municipio
        description: Lista com ID Município - IBGE 7 Dígitos
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: nome_regiao
        description: Nome da Grande Região
  - name: br_bd_diretorios_brasil__cnae_1
    description: Diretório da Classificação Nacional de Atividades Econômicas 1.0.
    columns:
      - name: cnae_1
        description: Classificação Nacional de Atividades Econômicas (CNAE) 1.0
        tests: [not_null]
      - name: descricao
        description: Descrição da CNAE 1.0
      - name: grupo
        description: Grupo
      - name: descricao_grupo
        description: Descrição do Grupo
      - name: divisao
        description: Divisão
      - name: descricao_divisao
        description: Descrição da Divisão
      - name: secao
        description: Seção
      - name: descricao_secao
        description: Descrição da Seção
  - name: br_bd_diretorios_brasil__cnae_2
    description: Diretório da Classificação Nacional de Atividades Econômicas 2.0.
    columns:
      - name: cnae_2
        description: Classificação Nacional de Atividades Econômicas (CNAE) 2.0
        tests: [not_null]
      - name: descricao
        description: Descrição da CNAE 2.0
      - name: grupo
        description: Grupo
      - name: descricao_grupo
        description: Descrição do Grupo
      - name: divisao
        description: Divisão
      - name: descricao_divisao
        description: Descrição da Divisão
      - name: secao
        description: Seção
      - name: descricao_secao
        description: Descrição da Seção
  - name: br_bd_diretorios_brasil__cnae_2_3_subclasses
    description: Diretório da Classificação Nacional de Atividades Econômicas - Subclasses
      2.3.
    columns:
      - name: cnae_2_3_subclasses
        description: Classificação Nacional de Atividades Econômicas (CNAE) - Subclasses
          2.3
        tests: [not_null]
      - name: descricao
        description: Descrição da CNAE - Subclasses 2.3
      - name: cnae_2
        description: Classificação Nacional de Atividades Econômicas (CNAE) 2.0
      - name: descricao_cnae_2
        description: Descrição da CNAE 2.0
      - name: grupo
        description: Grupo
      - name: descricao_grupo
        description: Descrição do Grupo
      - name: divisao
        description: Divisão
      - name: descricao_divisao
        description: Descrição da Divisão
      - name: secao
        description: Seção
      - name: descricao_secao
        description: Descrição da Seção
  - name: br_bd_diretorios_brasil__setor_censitario
    description: Description
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ano, id_setor_censitario]
    columns:
      - name: ano
        description: Ano
      - name: id_setor_censitario
        description: ID do setor censitário
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: id_rm
        description: ID da região metropolitana ou RIDE
      - name: nome_rm
        description: Nome da região metropolitana ou RIDE
      - name: id_distrito
        description: ID do distrito
      - name: nome_distrito
        description: Nome do distrito
      - name: id_subdistrito
        description: ID do subdistrito
      - name: nome_subdistrito
        description: Nome do subdistrito
      - name: id_bairro
        description: ID de bairro
      - name: nome_bairro
        description: Nome do bairro
      - name: sigla_uf
        description: Sigla do Estado
      - name: situacao_setor
        description: – ID de situação do setor - Situação urbana - IDs 1, 2 e 3; 1
          - Área urbanizada de cidade ou vila 2 - Área não urbanizada de cidade ou
          vila 3 - Área urbana isolada - Situação rural – IDs 4, 5, 6, 7 e 8; 4 -
          Aglomerado rural de extensão urbana 5 - Aglomerado rural isolado, povoado
          6 - Aglomerado rural isolado, núcleo 7 - Aglomerado rural isolado, outros
          aglomerados 8 - Zona rural, exclusive aglomerado rural
      - name: tipo_setor
        description: Tipo de setor censitário
      - name: id_microrregiao
        description: ID da microrregião
      - name: nome_microrregiao
        description: Nome da microrregião
      - name: id_mesorregiao
        description: ID da microrregião
      - name: nome_mesorregiao
        description: Nome da mesorregião
      - name: id_regiao_imediata
        description: ID da região geográfica imediata
      - name: nome_regiao_imediata
        description: Nome da região geográfica imediata
      - name: id_regiao_intermediaria
        description: ID da região geográfica intermediária
      - name: nome_regiao_intermediaria
        description: Nome da região geográfica intermediária
      - name: id_concentracao_urbana
        description: ID da Concentração Urbana
      - name: nome_concentracao_urbana
        description: Nome da Concentração Urbana
  - name: br_bd_diretorios_brasil__cid_10
    description: Diretório da Classificação Internacional de Doenças (CID) 10.
    columns:
      - name: subcategoria
        description: Subcategoria da CID-10
      - name: descricao_subcategoria
        description: Descrição da Subcategoria da CID-10
      - name: categoria
        description: Categoria da CID-10
      - name: descricao_categoria
        description: Descrição da Categoria da CID-10
      - name: capitulo
        description: Capítulo da CID-10
      - name: descricao_capitulo
        description: Descrição do Capítulo da CID-10
      - name: causa_violencia
        description: Causa - Violência
      - name: causa_overdose
        description: Causa - Overdose
      - name: cid_datasus
        description: Indica se a origem do CID-10 vem do DATASUS
