version: 2

models: 
  - name: br_bd_diretorios_brasil__empresa
    description: A tabela apresenta informações do Cadastro Nacional da Pessoa Jurídica (CNPJ), que é um banco de dados administrado pela Secretaria Especial da Receita Federal do Brasil (RFB). Esse cadastro armazena detalhes cadastrais de pessoas jurídicas e outras entidades relevantes para as administrações tributárias do governo federal, dos estados, do Distrito Federal e dos municípios.
    columns:
      - name: cnpj
        description: CNPJ
      - name: cnpj_basico
        description: CNPJ Básico (8 primeiros dígitos)
      - name: cnpj_ordem
        description: CNPJ Ordem
      - name: cnpj_dv
        description: CNPJ Dígito Verificador
      - name: razao_social
        description: Nome empresarial da pessoa jurídica
      - name: nome_fantasia
        description: Denomização Comercial
      - name: natureza_juridica
        description: Natureza Jurídica
      - name: ente_federativo
        description: Ente Federativo Responsável 
      - name: cnae_fiscal_principal
        description: CNAE Fiscal Principal
      - name: cnae_fiscal_secundaria
        description: CNAEs Fiscais Secundárias
      - name: capital_social
        description: Capital Social
      - name: porte
        description: Tipo do porte da empresa
      - name: matriz_filial
        description: Identificador entre Matriz e Filial 
      - name: situacao_cadastral
        description: Situação Cadastral
      - name: situacao_especial
        description: Situação Especial
      - name: opcao_simples
        description: Opção pelo Simples Nacional
      - name: opcao_mei
        description: Opção pelo MEI
      - name: cep
        description: CEP
      - name: tipo_logradouro
        description: Tipo de Logradouro
      - name: logradouro
        description: Logradouro
      - name: numero
        description: Número
      - name: complemento
        description: Complemento
      - name: bairro
        description: Bairro
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_code_iso3
        description: Sigla do País - ISO3
      - name: id_pais_me
        description: ID do país - Ministério da Economia
      - name: nome_pais_me
        description: Nome do país - Ministério da Economia
      - name: telefone_1
        description: Telefone (com DDD) 1
      - name: telefone_2
        description: Telefone (com DDD) 2
      - name: fax
        description: Fax (con DDD)
      - name: email
        description: Email
  - name: cep
    description: "Na tabela, é possível encontrar a numeração dos CEPs, juntamente com
    informações sobre suas localidades, tais como logradouros, bairros e cidades,
    além de complementos e identificação geográfica compostos pela latitude e longitude.
    Os dados foram obtidos através de uma base aberta no Kaggle e validados em relação
    aos seus pontos de geolocalização."
    columns:
      - name: cep
        description: Número do CEP
      - name: logradouro
        description: Logradouro
      - name: complemento
        description: Complemento do endereço
      - name: bairro
        description: Bairro
      - name: cidade
        description: Nome da cidade, distrito ou município
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: latitude
        description: Latitude do CEP
      - name: longitude
        description: Longitude do CEP
      - name: centroide
        description: Centróide do CEP
  - name: br_bd_diretorios_brasil__municipio
    description: 'Diretório ligando diversos códigos institucionais de municípios brasileiros: IBGE, Receita Federal, TSE, BCB, regiões, comarcas, região de saúde, etc.'
    columns:
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos 
      - name: id_municipio_6
        description: ID Município - IBGE 6 Dígitos
      - name: id_municipio_tse
        description: ID Município - Tribunal Superior Eleitoral (TSE)
      - name: id_municipio_rf
        description: ID Município - Receita Federal (RF) 
      - name: id_municipio_bcb
        description: ID Município - Banco Central do Brasil (BCB)
      - name: nome
        description: Nome do Município    
      - name: capital_uf
        description: Município é a Capital da Unidade da Federação
      - name: id_comarca
        description: ID Sede Comarca  
      - name: id_regiao_saude
        description: ID Região de Saúde
      - name: nome_regiao_saude
        description: Nome da Região de Saúde
      - name: id_regiao_imediata
        description: ID Região Imediata - IBGE  
      - name: nome_regiao_imediata
        description: Nome da Região Imediata
      - name: id_regiao_intermediaria
        description: ID Região Intermediária - IBGE
      - name: nome_regiao_intermediaria
        description: Nome da Região Intermediária 
      - name: id_microrregiao
        description: ID Microrregião - IBGE
      - name: nome_microrregiao
        description: Nome da Microrregião  
      - name: id_mesorregiao
        description: ID Mesorregião - IBGE
      - name: nome_mesorregiao
        description: Nome da Mesorregião   
      - name: ddd
        description: Código de Discagem Direta a Distância (DDD)
      - name: id_uf
        description: ID da Unidade da Federação - IBGE
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: nome_uf
        description: Nome da Unidade da Federação
      - name: nome_regiao
        description: Nome da Grande Região Brasileira
      - name: amazonia_legal
        description: Indicador se o município faz parte da Amazônia Legal
      - name: centroide
        description: Centróide do município
  - name: regiao_metropolitana
    description: 'A tabela contém os códigos identificadores e nomes de Região Metropolitana (RM), Aglomeração Urbana (AU), Região Integrada de Desenvolvimento (RIDE) entre outros recortes reunidas pelo IBGE'
    columns:
      - name: id_regiao_metropolitana
        description: ID Região Metropolitana - IBGE 
      - name: nome
        description: Nome da Região Metropolitana
      - name: id_recorte_metropolitano
        description: ID Recorte Metropolitano - IBGE
      - name: nome_recorte_metropolitano
        description: Nome do Recorte Metropolitano
      - name: id_subcategoria_metropolitana
        description: ID Subcategoria Metropolitana - IBGE
      - name: nome_subcategoria_metropolitana
        description: Nome Subcategoria Metropolitana    
      - name: tipo
        description: Tipo da Região 
      - name: sigla_uf
        description: Sigla da Unidade da Federação 
      - name: nome_regiao
        description: Nome da Grande Região