version: 2

models :
  - name: iptu
    description: O Geosampa disponibiliza a base completa do cadastro imobiliário fiscal relativo ao IPTU (Imposto Predial e Territorial Urbano) da cidade. São mais de 85 milhões de registros e 21,5 GB de informações sobre os imóveis de São Paulo.
    columns:
      - name: ano
        description: Ano
      - name: ano_construcao_corrigida
        description: Ano da construção corrigida
      - name: ano_inicio_vida_contribuinte
        description: Ano de início da vida do contribuinte
      - name: area_construida
        description: Área construída
      - name: area_ocupada
        description: Área ocupada
      - name: area_terreno
        description: Área do terreno
      - name: bairro
        description: Bairro do Imóvel
      - name: cep
        description: Número do CEP
      - name: complemento
        description: Complemento do endereço
      - name: data_cadastramento
        description: Data do Cadastramento
      - name: fator_obsolescencia
        description: Fator de obsolescencia
      - name: finalidade_imovel
        description: Finalidade do imóvel
      - name: fracao_ideal
        description: Fração ideal
      - name: logradouro
        description: Logradouro
      - name: mes_inicio_vida_contribuinte
        description: Mês de início da vida do contribuinte
      - name: numero_condominio
        description: Número do condomínio
      - name: numero_contribuinte
        description: Número do contribuinte do iptu
      - name: numero_imovel
        description: Número do Imóvel
      - name: numero_notificacao
        description: Número da notificação de lançamento (NL)
      - name: quantidade_esquina_imovel
        description: Quantidade de esquinas na frente do imóvel
      - name: quantidade_pavimento
        description: Quantidade de pavimentos
      - name: referencia_imovel
        description: Referencia do imóvel
      - name: testada_imovel
        description: Testada do imóvel
      - name: tipo_construcao
        description: Tipo de padrão da construção
      - name: tipo_terreno
        description: Tipo de terreno
      - name: valor_construcao
        description: Valor do metro quadrado de construção
      - name: valor_terreno
        description: Valor do metro quadrado do terreno