version: 2
models :
  - name: cotacoes
    description: Cotações negociadas diariamente, b3 é uma fonte completa e atualizada
      de informações sobre o mercado financeiro brasileiro. Inclui dados horário de
      fechamento do negócio, código referente ao negócio, preço e também quantidade
      de ações negociadas.
    columns:
      - name: acao_atualizacao
        description: Informa a ação de atualização que está ocorrendo (e.g. negócio
          novo, cancelado)
      - name: codigo_identificador_negocio
        description: Número do negócio
      - name: codigo_instrumento
        description: Código que identifica um instrumento negociado/registrado em
          bolsa de valores
      - name: codigo_participante_comprador
        description: Código comprador
      - name: codigo_participante_vendedor
        description: Código vendedor
      - name: data_negocio
        description: Data do pregão
      - name: data_referencia
        description: Data de referência da informação
      - name: hora_fechamento
        description: Hora (o instante) do negócio fechado (UTC-3)
      - name: preco_negocio
        description: Preço do negocio
      - name: quantidade_negociada
        description: Quantidade de ações negociadas
      - name: tipo_sessao_pregao
        description: "Tipo sessão do Pregão (e.g. sessão regular, after hours\r\n)"
