version: 2

models:
  - name: br_anatel_banda_larga_fixa__microdados
    description: "Microdados de banda larga fixa (também conhecido como Serviço de Comunicação Multimídia) a partir de 2007 que traz dados mensais acerca da empresa ofertante e das especificações técnicas do serviço."
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: cnpj
        description: Cadastro Nacional de Pessoa Jurídica
      - name: empresa
        description: Nome da empresa
      - name: porte_empresa
        description: Porte da empresa
      - name: tecnologia
        description: Tecnologia
      - name: transmissao
        description: Meios de transmissão
      - name: velocidade
        description: Velocidade contratada
      - name: produto
        description: Tipo de Produto
      - name: acessos
        description: Número total de contratos

  - name: br_anatel_banda_larga_fixa__densidade_brasil
    description: "Total de acessos e densidade por domicílio da Banda Larga Fixa no Brasil por mês e ano desde março de 2007"
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: densidade
        description: Densidade de acessos por 100 domicílios

  - name: br_anatel_banda_larga_fixa__densidade_uf
    description: "Total de acessos e densidade por domicílio da Banda Larga Fixa nos estados por mês e ano desde março de 2007"
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: densidade
        description: Densidade de acessos por 100 domicílios
        
  - name: br_anatel_banda_larga_fixa__densidade_municipio
    description: "Total de acessos e densidade por domicílio da Banda Larga Fixa nos estados por mês e ano desde março de 2007"
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos    
      - name: densidade
        description: Densidade de acessos por 100 domicílios

  - name: br_anatel_banda_larga_fixa__microdados_atualizado
    description: "Microdados de banda larga fixa (também conhecido como Serviço de Comunicação Multimídia) a partir de 2007 que traz dados mensais acerca da empresa ofertante e das especificações técnicas do serviço."
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: cnpj
        description: Cadastro Nacional de Pessoa Jurídica
      - name: empresa
        description: Nome da empresa
      - name: porte_empresa
        description: Porte da empresa
      - name: tecnologia
        description: Tecnologia
      - name: transmissao
        description: Meios de transmissão
      - name: velocidade
        description: Velocidade contratada
      - name: produto
        description: Tipo de Produto
      - name: acessos
        description: Número total de contratos

  - name: br_anatel_banda_larga_fixa__densidade_brasil_atualizado
    description: "Total de acessos e densidade por domicílio da Banda Larga Fixa no Brasil por mês e ano desde março de 2007"
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: densidade
        description: Densidade de acessos por 100 domicílios

  - name: br_anatel_banda_larga_fixa__densidade_uf_atualizado
    description: "Total de acessos e densidade por domicílio da Banda Larga Fixa nos estados por mês e ano desde março de 2007"
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: densidade
        description: Densidade de acessos por 100 domicílios
        
  - name: br_anatel_banda_larga_fixa__densidade_municipio_atualizado
    description: "Total de acessos e densidade por domicílio da Banda Larga Fixa nos estados por mês e ano desde março de 2007"
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos    
      - name: densidade
        description: Densidade de acessos por 100 domicílios