version: 2
models :
  - name: densidade_brasil
    description: Total de acessos e densidade por domicílio da Banda Larga Fixa no
      Brasil por mês e ano desde março de 2007
    columns:
      - name: ano
        description: Ano
      - name: densidade
        description: Densidade de acessos por 100 domicílios
      - name: mes
        description: Mês
  - name: densidade_municipio
    description: Total de acessos e densidade por domicílio da Banda Larga Fixa nos
      municípios brasileiros por mês e ano desde março de 2007.
    columns:
      - name: ano
        description: Ano
      - name: densidade
        description: Densidade de acessos por 100 domicílios
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
  - name: densidade_uf
    description: Total de acessos e densidade por domicílio da Banda Larga Fixa nos
      estados por mês e ano desde março de 2007
    columns:
      - name: ano
        description: Ano
      - name: densidade
        description: Densidade de acessos por 100 domicílios
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
