---
version: 2
models:
  - name: br_inep_sinopse_estatistica_educacao_basica__etapa_ensino_serie
    description: A base conta com o total de matrículas por município para todas as
      etapas e subetapas de ensino, além da discriminação dos anos para Anos Iniciais
      e Finais do Ensino Fundamental, bem como as série do Ensino Médio
    tests:
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: rede
        description: Rede Escolar (e.g. federal, estadual, municipal e privada)
      - name: etapa_ensino
        description: 'Etapa e/ou Sub-etapas de ensino (e.g. Creche, Pré-escola, Anos
          Iniciais, Anos Finais, Ensino Fundamental - EJA, ...) '
      - name: serie
        description: Série/Ano de ensino
      - name: quantidade_matricula
        description: Número de matrículas
  - name: br_inep_sinopse_estatistica_educacao_basica__faixa_etaria
    description: A base conta com o total de matrículas por município, etapa de ensino
      e grupo etário dos alunos
    tests:
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: etapa_ensino
        description: Etapa/nível de ensino
      - name: faixa_etaria
        description: Faixa Etária
      - name: quantidade_matricula
        description: Número de matrículas
  - name: br_inep_sinopse_estatistica_educacao_basica__localizacao
    description: A base conta com o total de matrículas por município, rede e localização
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: rede
        description: Rede Escolar (e.g. federal, estadual, municipal e privada)
      - name: etapa_ensino
        description: 'Etapa e/ou Sub-etapas de ensino (e.g. Creche, Pré-escola, Anos
          Iniciais, Anos Finais, Ensino Fundamental - EJA, ...) '
      - name: localizacao
        description: Localização (e.g. Zona Urbana, Zona Rural)
      - name: quantidade_matricula
        description: Número de matrículas
  - name: br_inep_sinopse_estatistica_educacao_basica__tempo_ensino
    description: A base conta com o total de matrículas por município para todas as
      etapas de ensino e o tempo ofertado de aulas, seja integral ou regular
    tests:
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: rede
        description: Rede Escolar (e.g. federal, estadual, municipal e privada)
      - name: tempo
        description: Classificação em tempo integral e tempo parcial
      - name: etapa_ensino
        description: 'Etapa e/ou Sub-etapas de ensino (e.g. Creche, Pré-escola, Anos
          Iniciais, Anos Finais, Ensino Fundamental - EJA, ...) '
      - name: quantidade_matricula
        description: Número de matrículas
  - name: br_inep_sinopse_estatistica_educacao_basica__sexo_raca_cor
    description: A base conta com o total de matrículas por município para todas as
      etapas de ensino, sexo e raça/cor
    tests:
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: etapa_ensino
        description: 'Etapa e/ou Sub-etapas de ensino (e.g. Creche, Pré-escola, Anos
          Iniciais, Anos Finais, Ensino Fundamental - EJA, ...) '
      - name: sexo
        description: Sexo
      - name: raca_cor
        description: Raça/Cor
      - name: quantidade_matricula
        description: Número de matrículas
