version: 2
models :
  - name: certidoes_criminais
    description: Dados extraídos das certidões criminais enviadas pelos candidatos
      ao TSE.
    columns:
      - name: ano
        description: Ano
      - name: extensao_arquivo
        description: Extensão do arquivo
      - name: id_candidato_bd
        description: ID Candidato - Base dos Dados
      - name: numero_paginas
        description: Número de páginas
      - name: sequencial_candidato
        description: Sequencial do candidato
      - name: sequencial_certidao
        description: Sequencial da certidão
      - name: sigla_uf
        description: Sigla da unidade da federação
      - name: texto
        description: Texto
