{{ 
  config(
    alias = 'historico_inscritos',
    schema='world_oceanos_mapeamento',
    materialized='table' )
 }}
SELECT
SAFE_CAST(ano AS INT64) ano,
SAFE_CAST(id_inscrito AS STRING) id_inscrito,
SAFE_CAST(responsavel_inscricao AS STRING) responsavel,
SAFE_CAST(nome_responsavel_inscricao AS STRING) nome_responsavel,
SAFE_CAST(titulo_livro AS STRING) titulo_livro,
SAFE_CAST(isbn AS STRING) isbn,
SAFE_CAST(genero_livro_categorias AS STRING) genero_livro,
SAFE_CAST(nome_pais_primeira_edicao AS STRING) nome_pais_primeira_edicao,
SAFE_CAST(tipo_publicacao AS STRING) tipo_publicacao,
SAFE_CAST(nome_autor_final AS STRING) autor_nome,
SAFE_CAST(genero_autor AS STRING) autor_genero,
SAFE_CAST(idade_autor AS STRING) autor_idade,
SAFE_CAST(nome_pais_autor AS STRING) autor_nome_pais,
SAFE_CAST(nacionaldade_autor AS STRING) autor_nacionalidade,
SAFE_CAST(indicador_atividade_economica_principal_autor AS STRING) autor_indicador_atividade_economica_principal,
SAFE_CAST(educacao_formal_autor AS STRING) autor_educacao_formal,
SAFE_CAST(indicador_publicacao_outras_obras AS BOOLEAN) autor_indicador_publicacao_outras_obras,
SAFE_CAST(quantidade_obras_publicadas AS INT64) autor_quantidade_obras_publicadas,
SAFE_CAST(nome_editora_final_3 AS STRING) editora_nome,
SAFE_CAST(pais_origem_editora AS STRING) editora_pais_origem,
SAFE_CAST(local_sede_editora AS STRING) editora_local_sede,
SAFE_CAST(ano_criacao_editora AS INT64) editora_ano_criacao,
SAFE_CAST(linha_predominante_editora AS STRING) editora_linha_predominante,
SAFE_CAST(canal_distribuicao_editora AS STRING) editora_canal_distribuicao,
SAFE_CAST(tiragem_edicao_editora AS STRING) editora_tiragem_edicao,
SAFE_CAST(financiamento_edicao_editora AS STRING) editora_financiamento_edicao,
SAFE_CAST(grupo_financiamento AS STRING) editora_grupo_financiamento,
SAFE_CAST(site_editora AS STRING) editora_site,
SAFE_CAST(indicador_outras_edicoes AS STRING) indicador_outras_edicoes,
SAFE_CAST(nome_editora_outras_edicoes AS STRING) outras_edicoes_nome_editora,
SAFE_CAST(ano_publicacao_outras_edicoes AS FLOAT64) outras_edicoes_ano_publicacao,
SAFE_CAST(nome_pais_outras_edicoes AS STRING) outras_edicoes_nome_pais,
SAFE_CAST(indicador_semifinalista_2 AS STRING) indicador_semifinalista,
SAFE_CAST(indicador_finalista_2 AS STRING) indicador_finalista,
SAFE_CAST(indicador_vencedor_2 AS STRING) indicador_vencedor,
FROM basedosdados-staging.world_oceanos_mapeamento_staging.historico_inscritos AS t
