version: 2
models :
  - name: microdados_movimentacao
    description: Contém dados de movimentações declaradas dentro do prazo com competência
      de declaração.
    columns:
      - name: ano
        description: Ano
      - name: categoria
        description: Categoria de trabalhador
      - name: cbo_2002
        description: Classificação Brasileira de Ocupações (CBO) - 2002
      - name: cnae_2_secao
        description: Classificação Nacional de Atividades Econômicas (CNAE 2.0 - Seção)
      - name: cnae_2_subclasse
        description: Subclasse do Código Nacional de Atividades Econômicas 2.0
      - name: grau_instrucao
        description: Grau de instrução ou escolaridade
      - name: horas_contratuais
        description: Horas contratuais
      - name: idade
        description: Idade do trabalhador
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: indicador_aprendiz
        description: Indicador de trabalhador aprendiz
      - name: indicador_fora_prazo
        description: Indicador fora do prazo
      - name: indicador_trabalho_intermitente
        description: Indicador de trabalhador intermitente
      - name: indicador_trabalho_parcial
        description: Indicador de movimentação referente a contrato parcial
      - name: mes
        description: Mês
      - name: origem_informacao
        description: Origem da Informação
      - name: raca_cor
        description: Raça ou Cor do Trabalhador
      - name: salario_mensal
        description: Salário mensal em moeda corrente
      - name: saldo_movimentacao
        description: Saldo de movimentação
      - name: sexo
        description: Sexo
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: tamanho_estabelecimento_janeiro
        description: Faixa de tamanho do estabelecimento em relação ao total de vínculos
          no início do ano
      - name: tipo_deficiencia
        description: Tipo de deficiência/Beneficiário habilitado
      - name: tipo_empregador
        description: Tipo de empregador
      - name: tipo_estabelecimento
        description: Tipo de estabelecimento
      - name: tipo_movimentacao
        description: Tipo de movimentação
  - name: microdados_movimentacao_excluida
    description: Contém dados de movimentações excluídas com competência de declaração.
    columns:
      - name: ano
        description: Ano
      - name: categoria
        description: Categoria de trabalhador
      - name: cbo_2002
        description: Classificação Brasileira de Ocupações (CBO) - 2002
      - name: cnae_2_secao
        description: Classificação Nacional de Atividades Econômicas (CNAE 2.0 - Seção)
      - name: cnae_2_subclasse
        description: Subclasse do Código Nacional de Atividades Econômicas 2.0
      - name: grau_instrucao
        description: Grau de instrução ou escolaridade
      - name: horas_contratuais
        description: Horas contratuais
      - name: idade
        description: Idade do trabalhador
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: indicador_aprendiz
        description: Indicador de trabalhador aprendiz
      - name: indicador_exclusao
        description: Indicador Exclusão
      - name: indicador_fora_prazo
        description: Indicador fora do prazo
      - name: indicador_trabalho_intermitente
        description: Indicador de trabalhador intermitente
      - name: indicador_trabalho_parcial
        description: Indicador de movimentação referente a contrato parcial
      - name: mes
        description: Mês
      - name: origem_informacao
        description: Origem da Informação
      - name: raca_cor
        description: Raça ou Cor do Trabalhador
      - name: salario_mensal
        description: Salário mensal em moeda corrente
      - name: saldo_movimentacao
        description: Saldo de movimentação
      - name: sexo
        description: Sexo
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: tamanho_estabelecimento_janeiro
        description: Faixa de tamanho do estabelecimento em relação ao total de vínculos
          no início do ano
      - name: tipo_deficiencia
        description: Tipo de deficiência/Beneficiário habilitado
      - name: tipo_empregador
        description: Tipo de empregador
      - name: tipo_estabelecimento
        description: Tipo de estabelecimento
      - name: tipo_movimentacao
        description: Tipo de movimentação
  - name: microdados_antigos
    description: Microdados públicos do CAGED (2007-2019)
    columns:
      - name: admitidos_desligados
        description: Admissão ou Desligamento (1 para admissão e 2 para desligamento)
      - name: ano
        description: Ano em que a movimentação foi declarada
      - name: bairros_fortaleza
        description: Bairros do município de Fortaleza
      - name: bairros_rj
        description: Bairros do município do Rio de Janeiro
      - name: bairros_sp
        description: Bairros do Municipio de São Paulo
      - name: cbo_2002
        description: Classificação Brasileira de Ocupações
      - name: cnae_1
        description: Classificação Nacional de Atividades Econômicas (CNAE) 1.0
      - name: cnae_2
        description: Classificação Nacional de Atividades Econômicas (CNAE) 2.0
      - name: cnae_2_subclasse
        description: Subclasse de Atividade Econômica, segundo classificação CNAE
          - versão 2.0 a partir de 2006
      - name: distritos_sp
        description: Distritos do município de São Paulo
      - name: faixa_emprego_inicio_janeiro
        description: Tamanho do estabelecimento em janeiro do ano de referência
      - name: grau_instrucao
        description: Grau de instrução ou escolaridade
      - name: idade
        description: Idade do trabalhador
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: id_municipio_6
        description: ID Município - IBGE 6 Dígitos
      - name: indicador_aprendiz
        description: Indicador de movimentação referente a contrato de aprendizagem
      - name: indicador_portador_deficiencia
        description: Indicador se o empregado/servidor de portador de deficiência
          habilitado ou beneficiário reabilitado
      - name: indicador_trabalho_intermitente
        description: Indicador de movimentação referente a contrato intermitente
      - name: indicador_trabalho_parcial
        description: Indicador de movimentação referente a contrato parcial
      - name: mes
        description: Mês em que a movimentação foi declarada
      - name: quantidade_horas_contratadas
        description: Quantidade de horas contratuais por semana
      - name: raca_cor
        description: Raça e Cor do Trabalhador - disponível a partir de 01/2007
      - name: regiao_administrativas_df
        description: Regiões Administrativas do Distrito Federal
      - name: regiao_administrativas_rj
        description: Regiões Administrativas do Rio de Janeiro
      - name: regiao_administrativas_sp
        description: Regiões Administrativas de São Paulo
      - name: regiao_corede
        description: Região Corede
      - name: regiao_corede_04
        description: Região Corede 04
      - name: regiao_gov_sp
        description: Região Governo de SP
      - name: regiao_senac_pr
        description: Região Senac PR
      - name: regiao_senai_pr
        description: Região Senai PR
      - name: regiao_senai_sp
        description: Região Senai SP
      - name: salario_mensal
        description: Salário mensal
      - name: saldo_movimentacao
        description: Saldo de movimentação
      - name: sexo
        description: Sexo
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: subregiao_senai_pr
        description: Sub-região Senai PR
      - name: subsetor_ibge
        description: Subsetor Econômico segundo IBGE
      - name: tempo_emprego
        description: Tempo de emprego do trabalhador
      - name: tipo_deficiencia
        description: Tipo de deficiência/Beneficiário habilitado
      - name: tipo_estabelecimento
        description: Tipo de estabelecimento
      - name: tipo_movimentacao_desagregado
        description: Tipo de movimentação
  - name: microdados_antigos_ajustes
    description: Microdados públicos de ajuste do CAGED (2007-2019)
    columns:
      - name: admitidos_desligados
        description: Admissão ou Desligamento
      - name: ano
        description: Ano em que a movimentação foi declarada
      - name: bairros_fortaleza
        description: Bairros do município de Fortaleza
      - name: bairros_rj
        description: Bairros do município do Rio de Janeiro
      - name: bairros_sp
        description: Bairros do Municipio de São Paulo
      - name: cbo_1994
        description: Classificação Brasileira de Ocupações 1994
      - name: cbo_2002
        description: Classificação Brasileira de Ocupações
      - name: cnae_1
        description: Classificação Nacional de Atividades Econômicas (CNAE) 1.0
      - name: cnae_2_subclasse
        description: Subclasse de Atividade Econômica, segundo classificação CNAE
          - versão 2.0 a partir de 2006
      - name: competencia_movimentacao
        description: Competência da qual é a movimentação
      - name: distritos_sp
        description: Distritos do município de São Paulo
      - name: faixa_emprego_inicio_janeiro
        description: Tamanho do estabelecimento em janeiro do ano de referência
      - name: grau_instrucao
        description: Grau de instrução ou escolaridade
      - name: idade
        description: Idade do trabalhador
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: id_municipio_6
        description: ID Município - IBGE 6 Dígitos
      - name: indicador_aprendiz
        description: Indicador de movimentação referente a contrato de aprendizagem
      - name: indicador_portador_deficiencia
        description: Indicador se o empregado/servidor de portador de deficiência
          habilitado ou beneficiário reabilitado
      - name: indicador_trabalho_intermitente
        description: Indicador de movimentação referente a contrato intermitente
      - name: indicador_trabalho_parcial
        description: Indicador de movimentação referente a contrato parcial
      - name: mes
        description: Mês em que a movimentação foi declarada
      - name: quantidade_horas_contratadas
        description: Quantidade de horas contratuais por semana
      - name: raca_cor
        description: Raça e Cor do Trabalhador
      - name: regiao_administrativas_df
        description: Regiões Administrativas do Distrito Federal
      - name: regiao_administrativas_rj
        description: Regiões Administrativas do Rio de Janeiro
      - name: regiao_administrativas_sp
        description: Regiões Administrativas de São Paulo
      - name: regiao_corede
        description: Região Corede
      - name: regiao_corede_04
        description: Região Corede 04
      - name: regiao_gov_sp
        description: Região Governo de SP
      - name: regiao_metropolitana_mte
        description: Região Metropolitana de localização do estabelecimento
      - name: regiao_senac_pr
        description: Região Senac PR
      - name: regiao_senai_pr
        description: Região Senai PR
      - name: regiao_senai_sp
        description: Região Senai SP
      - name: salario_mensal
        description: Salário mensal
      - name: saldo_movimentacao
        description: Saldo de movimentação
      - name: sexo
        description: Sexo
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: subregiao_senai_pr
        description: Sub-região Senai PR
      - name: subsetor_ibge
        description: Subsetor Econômico - IBGE
      - name: tempo_emprego
        description: Tempo de emprego do trabalhador
      - name: tipo_deficiencia
        description: Tipo de deficiência/Beneficiário habilitado
      - name: tipo_estabelecimento
        description: Tipo de estabelecimento
      - name: tipo_movimentacao_desagregado
        description: Tipo de movimentação
  - name: microdados_movimentacao_fora_prazo
    description: Contém dados de movimentações declaradas fora do prazo com competência
      de declaração.
    columns:
      - name: ano
        description: Ano
      - name: categoria
        description: Categoria de trabalhador
      - name: cbo_2002
        description: Classificação Brasileira de Ocupações (CBO) - 2002
      - name: cnae_2_secao
        description: Classificação Nacional de Atividades Econômicas (CNAE 2.0 - Seção)
      - name: cnae_2_subclasse
        description: Subclasse do Código Nacional de Atividades Econômicas 2.0
      - name: grau_instrucao
        description: Grau de instrução ou escolaridade
      - name: horas_contratuais
        description: Horas contratuais
      - name: idade
        description: Idade do trabalhador
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: indicador_aprendiz
        description: Indicador de trabalhador aprendiz
      - name: indicador_fora_prazo
        description: Indicador fora do prazo
      - name: indicador_trabalho_intermitente
        description: Indicador de trabalhador intermitente
      - name: indicador_trabalho_parcial
        description: Indicador de movimentação referente a contrato parcial
      - name: mes
        description: Mês
      - name: origem_informacao
        description: Origem da Informação
      - name: raca_cor
        description: Raça ou Cor do Trabalhador
      - name: salario_mensal
        description: Salário mensal em moeda corrente
      - name: saldo_movimentacao
        description: Saldo de movimentação
      - name: sexo
        description: Sexo
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: tamanho_estabelecimento_janeiro
        description: Faixa de tamanho do estabelecimento em relação ao total de vínculos
          no início do ano
      - name: tipo_deficiencia
        description: Tipo de deficiência/Beneficiário habilitado
      - name: tipo_empregador
        description: Tipo de empregador
      - name: tipo_estabelecimento
        description: Tipo de estabelecimento
      - name: tipo_movimentacao
        description: Tipo de movimentação