version: 2

models:
  - name: brasileirao_serie_a
    description: "Dados de 2003-03-29 até 2006-12-03 possuem somente as seguintes informações: data, horario, rodada, estadio, time_man, time_vis, gols_man, gols_vis. O motivo é que o site não disponibilizou outras informações.

A partir de 2007-05-03, informações mais completas foram disponibilizadas, contudo com algumas exceções.
    - tecnico_man e tecnico_vis possuem alguns valores vazios devido a mudança de padrão. Geralmente técnicos possui id = 0. Contudo quando o técnico é um ex-jogador, ele possuí um id específico. Em consequência da inconsistência no padrão do id dos técnicos, linhas em que esse erro ocorre as colunas valor_equipe_titular_man, valor_equipe_titular_vis, idade_media_titular_man, idade_media_titular_vis, também são afetadas e resultando em vazio;
    - Na data de 2016-12-11, rodada 38, a partida entre Chapecoense e Atlético-MG não ocorreu em decorrência do desastre que atingiu a equipe do Chapecoense na época, resultando assim em W.O. duplo;

Fonte: https://www.transfermarkt.com/campeonato-brasileiro-serie-a/startseite/wettbewerb/BRA1"
    columns:
      - name: ano_campeonato
        description: Ano do campeonato
      - name: data
        description: Data da partida
      - name: horario
        description: Horário da partida
      - name: rodada
        description: Rodada
      - name: estadio
        description: Estádio
      - name: arbitro
        description: Árbitro
      - name: publico
        description: Público presente
      - name: publico_max
        description: Público máximo
      - name: time_man
        description: Time mandante
      - name: time_vis
        description: Time visitante
      - name: tecnico_man
        description: Técnico do time mandante
      - name: tecnico_vis
        description: Técnico do time visitante
      - name: colocacao_man
        description: Colocação do time mandante
      - name: colocacao_vis
        description: Colocação do time visitante
      - name: valor_equipe_titular_man
        description: Valor da equipe titular do time mandante
      - name: valor_equipe_titular_vis
        description: Valor da equipe titular do time visitante
      - name: idade_media_titular_man
        description: Idade média da equipe titular do time mandante
      - name: idade_media_titular_vis
        description: Idade média da equipe titular do time visitante
      - name: gols_man
        description: Gols do time mandante
      - name: gols_vis
        description: Gols do time visitante
      - name: gols_1_tempo_man
        description: Gols no primeiro tempo do time mandante
      - name: gols_1_tempo_vis
        description: Gols no primeiro tempo do time visitante
      - name: escanteios_man
        description: Escanteios do time mandante
      - name: escanteios_vis
        description: Escanteios do time visitante
      - name: faltas_man
        description: Faltas feitas pelo time mandante
      - name: faltas_vis
        description: Faltas feitas pelo time visitante
      - name: chutes_bola_parada_man
        description: Chutes de bola parada do time mandante
      - name: chutes_bola_parada_vis
        description: Chutes de bola parada do time visitante
      - name: defesas_man
        description: Defesas do time mandante
      - name: defesas_vis
        description: Defesas do time visitante
      - name: impedimentos_man
        description: Impedimentos do time mandante
      - name: impedimentos_vis
        description: Impedimentos do time visitante
      - name: chutes_man
        description: Chutes do time mandante
      - name: chutes_vis
        description: Chutes do time visitante
      - name: chutes_fora_man
        description: Chutes fora do time mandante
      - name: chutes_fora_vis
        description: Chutes fora do time visitante